version: '3.8'

services:
  memgraph:
    image: memgraph/memgraph-platform:2.13.0-memgraph2.13.0-lab2.10.0-mage1.13
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MEMGRAPH_USER=user
      - MEMGRAPH_PASSWORD=pwd
      - MEMGRAPH=--storage-parallel-schema-recovery=true --storage-recovery-thread-count=24  --log-level=TRACE --also-log-to-stderr --storage-snapshot-on-exit=true --storage-snapshot-interval-sec=3600 --storage-snapshot-retention-count=4 --storage-wal-enabled=false --isolation-level=READ_COMMITTED --replication-restore-state-on-startup=true
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph
    restart: unless-stopped

volumes:
  memgraph-funds-flow-data: